name: fpm-deployment

# When a PR occurs, the fpm package of `stdlib` will be generated.
on: [push, pull_request]
env:
  GCC_V: "10"

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone fpm branch (stdlib-fpm)
      run: git clone -b stdlib-fpm https://github.com/fortran-lang/stdlib.git

    - name: Checkout stdlib code (master)
      uses: actions/checkout@v2
      with:
        path: "stdlib-master"

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: 3.x

    - name: Install fypp
      run: pip install --upgrade fypp

    - name: Generate stdlib-fpm package
      run: |
        ls
        sh ./stdlib-master/ci/fpm-deployment.sh

    - name: Install GFortran
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ env.GCC_V }} 100 \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${{ env.GCC_V }} \
        --slave /usr/bingcov gcov /usr/bin/gcov-${{ env.GCC_V }}
    - name: Install fpm latest release
      uses: fortran-lang/setup-fpm@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run fpm test
      run: |
        cp -r stdlib stdlib-fpm-test
        cd stdlib-fpm-test
        fpm test
    - name: Run fpm test (release)
      run: |
        cd stdlib-fpm-test
        fpm test --profile release
    # Update and deploy the f90 files generated by github-ci to the `stdlib-fpm` branch.
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      if: github.event_name != 'pull_request'
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: stdlib-fpm
        FOLDER: stdlib