name: CI

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install GFortran
      run: sudo apt-get install gfortran
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: test
      run: ctest --output-on-failure
